name: Bug Report
description: Report a bug or unexpected behavior in the VivanceData Learning Platform
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug. Please fill out the information below to help us investigate and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug you encountered...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear description of what actually happened.
      placeholder: What actually happened instead?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem. You can drag and drop images here.
      placeholder: Drag and drop screenshots here, or paste image URLs...
    validations:
      required: false

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser were you using when you encountered this bug?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Brave
        - Opera
        - Other (please specify in additional context)
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Which operating system were you using?
      options:
        - Windows 11
        - Windows 10
        - macOS Sonoma (14.x)
        - macOS Ventura (13.x)
        - macOS Monterey (12.x)
        - Ubuntu/Linux
        - iOS
        - Android
        - Other (please specify in additional context)
    validations:
      required: true

  - type: dropdown
    id: user-type
    attributes:
      label: Account Type
      description: Were you logged in when this occurred?
      options:
        - Logged in user
        - Guest (not logged in)
    validations:
      required: true

  - type: input
    id: course-lesson
    attributes:
      label: Course/Lesson (if applicable)
      description: If the bug occurred on a specific course or lesson, please provide the name or URL.
      placeholder: e.g., Machine Learning Fundamentals / Lesson 3
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, including error messages, console logs, or relevant details.
      placeholder: Any additional information that might help us understand and fix this bug...
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following before submitting.
      options:
        - label: I have searched existing issues to ensure this bug has not already been reported.
          required: true
        - label: I have provided all the requested information to the best of my ability.
          required: true
